"""add ml shadow fields to matches

Revision ID: 0199877f8573
Revises: 5939f713f552
Create Date: 2026-07-16 22:50:47.346469

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0199877f8573'
down_revision: Union[str, Sequence[str], None] = '5939f713f552'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches', sa.Column('ml_predicted_relevance', sa.Float(), nullable=True))
    op.add_column('matches', sa.Column('ml_predicted_grade', sa.Integer(), nullable=True))
    op.add_column('matches', sa.Column('ml_model_name', sa.String(length=100), nullable=True))
    op.add_column('matches', sa.Column('ml_model_version', sa.String(length=100), nullable=True))
    op.add_column('matches', sa.Column('ml_feature_set_identifier', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('matches', 'ml_feature_set_identifier')
    op.drop_column('matches', 'ml_model_version')
    op.drop_column('matches', 'ml_model_name')
    op.drop_column('matches', 'ml_predicted_grade')
    op.drop_column('matches', 'ml_predicted_relevance')
    # ### end Alembic commands ###
