"""create entity embeddings table

Revision ID: 180633e5bfbd
Revises: 515dff0a3a2c
Create Date: 2026-07-14 12:43:12.458010

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector
import pgvector

# revision identifiers, used by Alembic.
revision: str = '180633e5bfbd'
down_revision: Union[str, Sequence[str], None] = '515dff0a3a2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entity_embeddings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=100), nullable=False),
    sa.Column('model_name', sa.String(length=255), nullable=False),
    sa.Column('dimension', sa.Integer(), nullable=False),
    sa.Column('source_text', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entity_type', 'entity_id', 'model_name', name='uq_entity_embedding_type_id_model')
    )
    op.create_index(op.f('ix_entity_embeddings_entity_id'), 'entity_embeddings', ['entity_id'], unique=False)
    op.create_index(op.f('ix_entity_embeddings_entity_type'), 'entity_embeddings', ['entity_type'], unique=False)
    op.create_index(op.f('ix_entity_embeddings_id'), 'entity_embeddings', ['id'], unique=False)
    op.create_index(op.f('ix_entity_embeddings_model_name'), 'entity_embeddings', ['model_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_entity_embeddings_model_name'), table_name='entity_embeddings')
    op.drop_index(op.f('ix_entity_embeddings_id'), table_name='entity_embeddings')
    op.drop_index(op.f('ix_entity_embeddings_entity_type'), table_name='entity_embeddings')
    op.drop_index(op.f('ix_entity_embeddings_entity_id'), table_name='entity_embeddings')
    op.drop_table('entity_embeddings')
    # ### end Alembic commands ###
