"""add unique constraint to matches

Revision ID: 302987329720
Revises: a5474392bc56
Create Date: 2026-07-10 00:57:09.863420

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '302987329720'
down_revision: Union[str, Sequence[str], None] = 'a5474392bc56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_match_resume_job', 'matches', ['resume_id', 'job_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_match_resume_job', 'matches', type_='unique')
    # ### end Alembic commands ###
