"""add algorithm version to matches

Revision ID: 31c0a09176b4
Revises: 180633e5bfbd
Create Date: 2026-07-15 00:21:10.126944

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31c0a09176b4'
down_revision: Union[str, Sequence[str], None] = '180633e5bfbd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches', sa.Column('algorithm_version', sa.String(length=100), nullable=False, server_default="hybrid-v1"))
    op.create_index(op.f('ix_matches_algorithm_version'), 'matches', ['algorithm_version'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_matches_algorithm_version'), table_name='matches')
    op.drop_column('matches', 'algorithm_version')
    # ### end Alembic commands ###
