"""create match feedback table

Revision ID: 5939f713f552
Revises: 954399017cd4
Create Date: 2026-07-15 23:15:46.593815

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5939f713f552'
down_revision: Union[str, Sequence[str], None] = '954399017cd4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('match_feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('resume_id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('relevance_grade', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'resume_id', 'job_id', name='uq_match_feedback_user_resume_job')
    )
    op.create_index(op.f('ix_match_feedback_id'), 'match_feedback', ['id'], unique=False)
    op.create_index(op.f('ix_match_feedback_job_id'), 'match_feedback', ['job_id'], unique=False)
    op.create_index(op.f('ix_match_feedback_resume_id'), 'match_feedback', ['resume_id'], unique=False)
    op.create_index(op.f('ix_match_feedback_user_id'), 'match_feedback', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_match_feedback_user_id'), table_name='match_feedback')
    op.drop_index(op.f('ix_match_feedback_resume_id'), table_name='match_feedback')
    op.drop_index(op.f('ix_match_feedback_job_id'), table_name='match_feedback')
    op.drop_index(op.f('ix_match_feedback_id'), table_name='match_feedback')
    op.drop_table('match_feedback')
    # ### end Alembic commands ###
