"""create job ingestion runs table

Revision ID: 5f2e1a76484d
Revises: 8b682d20bcbb
Create Date: 2026-07-14 01:37:53.321082

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5f2e1a76484d'
down_revision: Union[str, Sequence[str], None] = '8b682d20bcbb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_ingestion_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.String(length=255), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('fetched_count', sa.Integer(), nullable=False),
    sa.Column('created_count', sa.Integer(), nullable=False),
    sa.Column('updated_count', sa.Integer(), nullable=False),
    sa.Column('failed_count', sa.Integer(), nullable=False),
    sa.Column('errors', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_ingestion_runs_id'), 'job_ingestion_runs', ['id'], unique=False)
    op.create_index(op.f('ix_job_ingestion_runs_source'), 'job_ingestion_runs', ['source'], unique=False)
    op.create_index(op.f('ix_job_ingestion_runs_status'), 'job_ingestion_runs', ['status'], unique=False)
    op.create_index(op.f('ix_job_ingestion_runs_task_id'), 'job_ingestion_runs', ['task_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_job_ingestion_runs_task_id'), table_name='job_ingestion_runs')
    op.drop_index(op.f('ix_job_ingestion_runs_status'), table_name='job_ingestion_runs')
    op.drop_index(op.f('ix_job_ingestion_runs_source'), table_name='job_ingestion_runs')
    op.drop_index(op.f('ix_job_ingestion_runs_id'), table_name='job_ingestion_runs')
    op.drop_table('job_ingestion_runs')
    # ### end Alembic commands ###
