"""create cv improvements table

Revision ID: 5f48bc1c8aa5
Revises: 61b50e9adeeb
Create Date: 2026-07-07 21:58:10.498868

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5f48bc1c8aa5'
down_revision: Union[str, Sequence[str], None] = '61b50e9adeeb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cv_improvements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resume_id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cv_improvements_id'), 'cv_improvements', ['id'], unique=False)
    op.create_index(op.f('ix_cv_improvements_job_id'), 'cv_improvements', ['job_id'], unique=False)
    op.create_index(op.f('ix_cv_improvements_resume_id'), 'cv_improvements', ['resume_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cv_improvements_resume_id'), table_name='cv_improvements')
    op.drop_index(op.f('ix_cv_improvements_job_id'), table_name='cv_improvements')
    op.drop_index(op.f('ix_cv_improvements_id'), table_name='cv_improvements')
    op.drop_table('cv_improvements')
    # ### end Alembic commands ###
