"""add raw text to resumes

Revision ID: 653b5f61177d
Revises: 61e2987691be
Create Date: 2026-07-03 16:18:12.254917

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '653b5f61177d'
down_revision: Union[str, Sequence[str], None] = '61e2987691be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resumes', sa.Column('raw_text', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resumes', 'raw_text')
    # ### end Alembic commands ###
