"""add job ingestion fields

Revision ID: 8b682d20bcbb
Revises: 302987329720
Create Date: 2026-07-14 00:45:00.046475

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b682d20bcbb'
down_revision: Union[str, Sequence[str], None] = '302987329720'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('external_id', sa.String(length=255), nullable=True))
    op.add_column('jobs', sa.Column('normalized_title', sa.String(length=255), nullable=True))
    op.add_column('jobs', sa.Column('normalized_company_name', sa.String(length=255), nullable=True))
    op.add_column('jobs', sa.Column('normalized_location', sa.String(length=255), nullable=True))
    op.add_column('jobs', sa.Column('fingerprint', sa.String(length=64), nullable=True))
    op.add_column('jobs', sa.Column('updated_at', sa.DateTime(),server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False))
    op.create_index(op.f('ix_jobs_external_id'), 'jobs', ['external_id'], unique=False)
    op.create_index(op.f('ix_jobs_fingerprint'), 'jobs', ['fingerprint'], unique=True)
    op.create_index(op.f('ix_jobs_normalized_company_name'), 'jobs', ['normalized_company_name'], unique=False)
    op.create_index(op.f('ix_jobs_normalized_title'), 'jobs', ['normalized_title'], unique=False)
    op.create_unique_constraint('uq_jobs_fingerprint', 'jobs', ['fingerprint'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_jobs_fingerprint', 'jobs', type_='unique')
    op.drop_index(op.f('ix_jobs_normalized_title'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_normalized_company_name'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_fingerprint'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_external_id'), table_name='jobs')
    op.drop_column('jobs', 'updated_at')
    op.drop_column('jobs', 'fingerprint')
    op.drop_column('jobs', 'normalized_location')
    op.drop_column('jobs', 'normalized_company_name')
    op.drop_column('jobs', 'normalized_title')
    op.drop_column('jobs', 'external_id')
    # ### end Alembic commands ###
