"""add unique constraint to cv improvements

Revision ID: a5474392bc56
Revises: cded9b5b2281
Create Date: 2026-07-10 00:47:56.698921

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5474392bc56'
down_revision: Union[str, Sequence[str], None] = 'cded9b5b2281'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_cv_improvement_resume_job_language', 'cv_improvements', ['resume_id', 'job_id', 'language'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_cv_improvement_resume_job_language', 'cv_improvements', type_='unique')
    # ### end Alembic commands ###
