"""add ml shadow status fields

Revision ID: b2b878e46b16
Revises: 0199877f8573
Create Date: 2026-07-16 23:43:18.922096

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2b878e46b16'
down_revision: Union[str, Sequence[str], None] = '0199877f8573'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches', sa.Column('ml_prediction_status', sa.String(length=50), nullable=True))
    op.add_column('matches', sa.Column('ml_prediction_error', sa.String(length=1000), nullable=True))
    op.create_index(op.f('ix_matches_ml_prediction_status'), 'matches', ['ml_prediction_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_matches_ml_prediction_status'), table_name='matches')
    op.drop_column('matches', 'ml_prediction_error')
    op.drop_column('matches', 'ml_prediction_status')
    # ### end Alembic commands ###
