"""add language to cv improvements

Revision ID: cded9b5b2281
Revises: 5f48bc1c8aa5
Create Date: 2026-07-09 23:49:59.935865

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cded9b5b2281'
down_revision: Union[str, Sequence[str], None] = '5f48bc1c8aa5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "cv_improvements",
        sa.Column(
            "language",
            sa.String(length=10),
            server_default="en",
            nullable=False,
        ),
    )
    op.create_index(op.f('ix_cv_improvements_language'), 'cv_improvements', ['language'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cv_improvements_language'), table_name='cv_improvements')
    op.drop_column('cv_improvements', 'language')
    # ### end Alembic commands ###
