"""add knowledge cache observability fields

Revision ID: dfd5b2f948fc
Revises: c4bc3915b4e0
Create Date: 2026-07-21 23:20:50.614241

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dfd5b2f948fc'
down_revision: Union[str, Sequence[str], None] = 'c4bc3915b4e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rag_runs', sa.Column('cache_enabled', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('rag_runs', sa.Column('cache_hit', sa.Boolean(), nullable=True))
    op.add_column('rag_runs', sa.Column('cache_provider', sa.String(length=50), nullable=True))
    op.add_column('rag_runs', sa.Column('cache_read_latency_ms', sa.Float(), nullable=True))
    op.add_column('rag_runs', sa.Column('cache_write_latency_ms', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rag_runs', 'cache_write_latency_ms')
    op.drop_column('rag_runs', 'cache_read_latency_ms')
    op.drop_column('rag_runs', 'cache_provider')
    op.drop_column('rag_runs', 'cache_hit')
    op.drop_column('rag_runs', 'cache_enabled')
    # ### end Alembic commands ###
