"""create rag observability tables

Revision ID: eb4cf8841cd9
Revises: 60e8dec2d69a
Create Date: 2026-07-19 00:58:37.757889

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'eb4cf8841cd9'
down_revision: Union[str, Sequence[str], None] = '60e8dec2d69a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rag_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('generation_status', sa.String(length=50), nullable=False),
    sa.Column('sufficient_context', sa.Boolean(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('retrieval_limit', sa.Integer(), nullable=False),
    sa.Column('minimum_similarity', sa.Float(), nullable=False),
    sa.Column('retrieval_result_count', sa.Integer(), nullable=False),
    sa.Column('context_source_count', sa.Integer(), nullable=False),
    sa.Column('context_character_count', sa.Integer(), nullable=False),
    sa.Column('embedding_provider', sa.String(length=100), nullable=True),
    sa.Column('embedding_model_name', sa.String(length=255), nullable=True),
    sa.Column('llm_provider', sa.String(length=100), nullable=True),
    sa.Column('llm_model_name', sa.String(length=255), nullable=True),
    sa.Column('prompt_name', sa.String(length=255), nullable=False),
    sa.Column('prompt_version', sa.String(length=50), nullable=False),
    sa.Column('retrieval_latency_ms', sa.Float(), nullable=True),
    sa.Column('context_build_latency_ms', sa.Float(), nullable=True),
    sa.Column('prompt_build_latency_ms', sa.Float(), nullable=True),
    sa.Column('llm_latency_ms', sa.Float(), nullable=True),
    sa.Column('total_latency_ms', sa.Float(), nullable=True),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('total_tokens', sa.Integer(), nullable=True),
    sa.Column('citations', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('validation_errors', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('error_type', sa.String(length=255), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rag_runs_category'), 'rag_runs', ['category'], unique=False)
    op.create_index(op.f('ix_rag_runs_created_at'), 'rag_runs', ['created_at'], unique=False)
    op.create_index(op.f('ix_rag_runs_embedding_model_name'), 'rag_runs', ['embedding_model_name'], unique=False)
    op.create_index(op.f('ix_rag_runs_generation_status'), 'rag_runs', ['generation_status'], unique=False)
    op.create_index(op.f('ix_rag_runs_id'), 'rag_runs', ['id'], unique=False)
    op.create_index(op.f('ix_rag_runs_language'), 'rag_runs', ['language'], unique=False)
    op.create_index(op.f('ix_rag_runs_llm_model_name'), 'rag_runs', ['llm_model_name'], unique=False)
    op.create_index(op.f('ix_rag_runs_total_latency_ms'), 'rag_runs', ['total_latency_ms'], unique=False)
    op.create_index(op.f('ix_rag_runs_user_id'), 'rag_runs', ['user_id'], unique=False)
    op.create_table('rag_run_chunks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rag_run_id', sa.Integer(), nullable=False),
    sa.Column('knowledge_chunk_id', sa.Integer(), nullable=True),
    sa.Column('knowledge_document_id', sa.Integer(), nullable=True),
    sa.Column('source_number', sa.Integer(), nullable=False),
    sa.Column('retrieval_rank', sa.Integer(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('document_title', sa.Text(), nullable=False),
    sa.Column('chunk_content', sa.Text(), nullable=False),
    sa.Column('similarity_score', sa.Float(), nullable=False),
    sa.Column('was_included_in_context', sa.Boolean(), nullable=False),
    sa.Column('was_cited', sa.Boolean(), nullable=False),
    sa.Column('chunk_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['knowledge_chunk_id'], ['knowledge_chunks.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['knowledge_document_id'], ['knowledge_documents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['rag_run_id'], ['rag_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rag_run_id', 'source_number', name='uq_rag_run_chunks_run_source_number')
    )
    op.create_index(op.f('ix_rag_run_chunks_id'), 'rag_run_chunks', ['id'], unique=False)
    op.create_index(op.f('ix_rag_run_chunks_knowledge_chunk_id'), 'rag_run_chunks', ['knowledge_chunk_id'], unique=False)
    op.create_index(op.f('ix_rag_run_chunks_knowledge_document_id'), 'rag_run_chunks', ['knowledge_document_id'], unique=False)
    op.create_index(op.f('ix_rag_run_chunks_rag_run_id'), 'rag_run_chunks', ['rag_run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rag_run_chunks_rag_run_id'), table_name='rag_run_chunks')
    op.drop_index(op.f('ix_rag_run_chunks_knowledge_document_id'), table_name='rag_run_chunks')
    op.drop_index(op.f('ix_rag_run_chunks_knowledge_chunk_id'), table_name='rag_run_chunks')
    op.drop_index(op.f('ix_rag_run_chunks_id'), table_name='rag_run_chunks')
    op.drop_table('rag_run_chunks')
    op.drop_index(op.f('ix_rag_runs_user_id'), table_name='rag_runs')
    op.drop_index(op.f('ix_rag_runs_total_latency_ms'), table_name='rag_runs')
    op.drop_index(op.f('ix_rag_runs_llm_model_name'), table_name='rag_runs')
    op.drop_index(op.f('ix_rag_runs_language'), table_name='rag_runs')
    op.drop_index(op.f('ix_rag_runs_id'), table_name='rag_runs')
    op.drop_index(op.f('ix_rag_runs_generation_status'), table_name='rag_runs')
    op.drop_index(op.f('ix_rag_runs_embedding_model_name'), table_name='rag_runs')
    op.drop_index(op.f('ix_rag_runs_created_at'), table_name='rag_runs')
    op.drop_index(op.f('ix_rag_runs_category'), table_name='rag_runs')
    op.drop_table('rag_runs')
    # ### end Alembic commands ###
