"""create rag answer evaluations table

Revision ID: fd60ed42eadc
Revises: dfd5b2f948fc
Create Date: 2026-07-22 20:22:04.528138

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fd60ed42eadc'
down_revision: Union[str, Sequence[str], None] = 'dfd5b2f948fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rag_answer_evaluations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rag_run_id', sa.Integer(), nullable=False),
    sa.Column('overall_score', sa.Float(), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('evaluator_count', sa.Integer(), nullable=False),
    sa.Column('failed_evaluator_names', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('results', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('evaluation_profile', sa.String(length=100), nullable=False),
    sa.Column('evaluator_version', sa.String(length=50), nullable=False),
    sa.Column('judge_provider', sa.String(length=100), nullable=True),
    sa.Column('judge_model', sa.String(length=150), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['rag_run_id'], ['rag_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_rag_answer_evaluations_created_at', 'rag_answer_evaluations', ['created_at'], unique=False)
    op.create_index(op.f('ix_rag_answer_evaluations_id'), 'rag_answer_evaluations', ['id'], unique=False)
    op.create_index('ix_rag_answer_evaluations_passed', 'rag_answer_evaluations', ['passed'], unique=False)
    op.create_index('ix_rag_answer_evaluations_rag_run_id', 'rag_answer_evaluations', ['rag_run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_rag_answer_evaluations_rag_run_id', table_name='rag_answer_evaluations')
    op.drop_index('ix_rag_answer_evaluations_passed', table_name='rag_answer_evaluations')
    op.drop_index(op.f('ix_rag_answer_evaluations_id'), table_name='rag_answer_evaluations')
    op.drop_index('ix_rag_answer_evaluations_created_at', table_name='rag_answer_evaluations')
    op.drop_table('rag_answer_evaluations')
    # ### end Alembic commands ###
